// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniSupermarket.API.Data;

#nullable disable

namespace MiniSupermarket.API.Migrations
{
    [DbContext(typeof(SupermarketDbContext))]
    [Migration("20261003114840_ChangeDatabase")]
    partial class ChangeDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Bánh kẹo nhập khẩu",
                            Description = "Các loại bánh quy, chocolate, kẹo và đồ ngọt nhập khẩu cao cấp"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Chocolate",
                            Description = "Chocolate đen, chocolate sữa và chocolate cao cấp từ các thương hiệu quốc tế"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Phô mai & Bơ",
                            Description = "Phô mai, bơ và các sản phẩm từ sữa nhập khẩu"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Thịt nguội & Xúc xích",
                            Description = "Thịt nguội, xúc xích, salami và các sản phẩm thịt nhập khẩu"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Thực phẩm đóng hộp",
                            Description = "Cá hộp, thịt hộp, rau củ đóng hộp và thực phẩm chế biến sẵn"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Mì & Pasta",
                            Description = "Mì Ý, pasta, mì ramen và các sản phẩm mì nhập khẩu"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Sốt & Gia vị",
                            Description = "Dầu olive, nước sốt, tương ớt, tiêu, muối và gia vị nhập khẩu"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Đồ uống nhập khẩu",
                            Description = "Nước trái cây, nước khoáng, nước ngọt và các loại đồ uống quốc tế"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Cà phê & Trà",
                            Description = "Cà phê hạt, cà phê rang xay, trà túi lọc và trà cao cấp nhập khẩu"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Ngũ cốc & Thực phẩm ăn sáng",
                            Description = "Ngũ cốc, yến mạch, granola và các sản phẩm ăn sáng nhập khẩu"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Đồ ăn nhẹ",
                            Description = "Snack, khoai tây chiên, hạt dinh dưỡng và đồ ăn nhẹ nhập khẩu"
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "Thực phẩm đông lạnh",
                            Description = "Pizza, hải sản, thịt và các sản phẩm đông lạnh nhập khẩu"
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryName = "Thực phẩm hữu cơ",
                            Description = "Các sản phẩm thực phẩm hữu cơ và sản phẩm tự nhiên nhập khẩu"
                        },
                        new
                        {
                            CategoryId = 14,
                            CategoryName = "Trái cây nhập khẩu",
                            Description = "Các loại trái cây cao cấp nhập khẩu từ Mỹ, Úc, New Zealand và châu Âu"
                        },
                        new
                        {
                            CategoryId = 15,
                            CategoryName = "Thực phẩm cao cấp Gourmet",
                            Description = "Các sản phẩm đặc sản và thực phẩm cao cấp phục vụ khách hàng Gourmet"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MembershipRank")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "25 Nguyễn Huệ, Quận 1, TP.HCM",
                            CustomerName = "Nguyễn Văn An",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0901122334",
                            RewardPoints = 1500
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "118 Võ Văn Tần, Quận 3, TP.HCM",
                            CustomerName = "Trần Thị Bình",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0918877665",
                            RewardPoints = 500
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "72 Nguyễn Trãi, Quận 5, TP.HCM",
                            CustomerName = "Lê Văn Cường",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0983344556",
                            RewardPoints = 100
                        },
                        new
                        {
                            CustomerId = 4,
                            Address = "156 Thành Thái, Quận 10, TP.HCM",
                            CustomerName = "Phạm Thị Dung",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0905678123",
                            RewardPoints = 2300
                        },
                        new
                        {
                            CustomerId = 5,
                            Address = "43 Điện Biên Phủ, Quận Bình Thạnh, TP.HCM",
                            CustomerName = "Hoàng Văn Đức",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0912345678",
                            RewardPoints = 800
                        },
                        new
                        {
                            CustomerId = 6,
                            Address = "89 Phạm Văn Đồng, Quận Gò Vấp, TP.HCM",
                            CustomerName = "Võ Thị Hà",
                            MembershipRank = "Kim Cương",
                            PhoneNumber = "0987654321",
                            RewardPoints = 3200
                        },
                        new
                        {
                            CustomerId = 7,
                            Address = "215 Cộng Hòa, Quận Tân Bình, TP.HCM",
                            CustomerName = "Đặng Văn Giang",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0909876543",
                            RewardPoints = 250
                        },
                        new
                        {
                            CustomerId = 8,
                            Address = "36 Phan Đình Phùng, Quận Phú Nhuận, TP.HCM",
                            CustomerName = "Bùi Thị Hương",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0913456789",
                            RewardPoints = 1200
                        },
                        new
                        {
                            CustomerId = 9,
                            Address = "102 Nguyễn Thị Thập, Quận 7, TP.HCM",
                            CustomerName = "Đỗ Văn Khải",
                            MembershipRank = "Kim Cương",
                            PhoneNumber = "0981234567",
                            RewardPoints = 4500
                        },
                        new
                        {
                            CustomerId = 10,
                            Address = "68 Hậu Giang, Quận 6, TP.HCM",
                            CustomerName = "Nguyễn Thị Lan",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0903456789",
                            RewardPoints = 150
                        },
                        new
                        {
                            CustomerId = 11,
                            Address = "145 Võ Văn Ngân, TP. Thủ Đức, TP.HCM",
                            CustomerName = "Trương Văn Minh",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0915678901",
                            RewardPoints = 1800
                        },
                        new
                        {
                            CustomerId = 12,
                            Address = "234 Lê Văn Khương, Quận 12, TP.HCM",
                            CustomerName = "Phan Thị Mai",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0986789012",
                            RewardPoints = 700
                        },
                        new
                        {
                            CustomerId = 13,
                            Address = "57 Lũy Bán Bích, Quận Tân Phú, TP.HCM",
                            CustomerName = "Lý Văn Nam",
                            MembershipRank = "Kim Cương",
                            PhoneNumber = "0907890123",
                            RewardPoints = 5000
                        },
                        new
                        {
                            CustomerId = 14,
                            Address = "321 Tỉnh Lộ 10, Quận Bình Tân, TP.HCM",
                            CustomerName = "Huỳnh Thị Phương",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0918901234",
                            RewardPoints = 350
                        },
                        new
                        {
                            CustomerId = 15,
                            Address = "78 Nguyễn Hữu Trí, Huyện Bình Chánh, TP.HCM",
                            CustomerName = "Mai Văn Quân",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0989012345",
                            RewardPoints = 2600
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Barcode = "GOU000001",
                            CategoryId = 2,
                            Price = 185000m,
                            ProductName = "Chocolate Lindt Excellence Dark 70%",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 2,
                            Barcode = "GOU000002",
                            CategoryId = 1,
                            Price = 145000m,
                            ProductName = "Bánh quy bơ Walkers Shortbread",
                            StockQuantity = 80
                        },
                        new
                        {
                            ProductId = 3,
                            Barcode = "GOU000003",
                            CategoryId = 3,
                            Price = 320000m,
                            ProductName = "Phô mai Cheddar nhập khẩu Anh",
                            StockQuantity = 35
                        },
                        new
                        {
                            ProductId = 4,
                            Barcode = "GOU000004",
                            CategoryId = 4,
                            Price = 285000m,
                            ProductName = "Xúc xích Đức Bratwurst",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 5,
                            Barcode = "GOU000005",
                            CategoryId = 5,
                            Price = 125000m,
                            ProductName = "Cá ngừ ngâm dầu Rio Mare",
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 6,
                            Barcode = "GOU000006",
                            CategoryId = 6,
                            Price = 78000m,
                            ProductName = "Pasta Barilla Spaghetti No.5",
                            StockQuantity = 150
                        },
                        new
                        {
                            ProductId = 7,
                            Barcode = "GOU000007",
                            CategoryId = 7,
                            Price = 265000m,
                            ProductName = "Dầu Olive Extra Virgin Bertolli",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 8,
                            Barcode = "GOU000008",
                            CategoryId = 8,
                            Price = 175000m,
                            ProductName = "Nước ép táo nguyên chất Martinelli's",
                            StockQuantity = 45
                        },
                        new
                        {
                            ProductId = 9,
                            Barcode = "GOU000009",
                            CategoryId = 9,
                            Price = 395000m,
                            ProductName = "Cà phê Lavazza Qualità Oro",
                            StockQuantity = 55
                        },
                        new
                        {
                            ProductId = 10,
                            Barcode = "GOU000010",
                            CategoryId = 10,
                            Price = 165000m,
                            ProductName = "Ngũ cốc Kellogg's Corn Flakes",
                            StockQuantity = 70
                        },
                        new
                        {
                            ProductId = 11,
                            Barcode = "GOU000011",
                            CategoryId = 11,
                            Price = 295000m,
                            ProductName = "Hạt hạnh nhân rang Kirkland",
                            StockQuantity = 65
                        },
                        new
                        {
                            ProductId = 12,
                            Barcode = "GOU000012",
                            CategoryId = 12,
                            Price = 185000m,
                            ProductName = "Pizza đông lạnh Dr. Oetker",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 13,
                            Barcode = "GOU000013",
                            CategoryId = 13,
                            Price = 850000m,
                            ProductName = "Mật ong hữu cơ Manuka",
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductId = 14,
                            Barcode = "GOU000014",
                            CategoryId = 14,
                            Price = 220000m,
                            ProductName = "Nho xanh không hạt nhập khẩu Mỹ",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 15,
                            Barcode = "GOU000015",
                            CategoryId = 15,
                            Price = 1250000m,
                            ProductName = "Gan ngỗng Foie Gras Gourmet",
                            StockQuantity = 15
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
